-- CREATE TABLE IF NOT EXISTS account_plan(
--     id integer primary key auto increment,
--    account VARCHAR(81) NOT NULL,
--    acc_name VARCHAR(142) NOT NULL,
--    acc_type VARCHAR(12)
-- );
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1','Conturi de capitaluri, provizioane, împrumuturi şi datorii asimilate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('10','Capital şi rezerve','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('101','Capital','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1011','Capital subscris nevărsat','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1012','Capital subscris vărsat','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1015','Patrimoniul regiei','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1016','Patrimoniul public','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1017','Patrimoniul privat','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1018','Patrimoniul institutelor naţionale de cercetare - dezvoltare','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('103','Alte elemente de capitaluri proprii','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1031','Beneficii acordate angajaţilor sub forma instrumentelor de capitaluri proprii','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1033','Diferenţe de curs valutar în relaţie cu investiţia netă într-o entitate străină','bifunctional');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1038','Diferenţe din modificarea valorii juste a activelor financiare disponibile în vederea vânzării şi alte elemente de capitaluri proprii','bifunctional');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('104','Prime de capital','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1041','Prime de emisiune','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1042','Prime de fuziune/divizare','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1043','Prime de aport','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1044','Prime de conversie a obligaţiunilor în acţiuni','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('105','Rezerve din reevaluare','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('106','Rezerve','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1061','Rezerve legale','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1063','Rezerve statutare sau contractuale','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1068','Alte rezerve','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('107','Diferenţe de curs valutar din conversie','bifunctional');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('108','Interese care nu controlează','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1081','Interese care nu controlează - rezultatul exerciţiului financiar','bifunctional');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1082','Interese care nu controlează - alte capitaluri proprii','bifunctional');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('109','Acţiuni proprii','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1091','Acţiuni proprii deţinute pe termen scurt','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1092','Acţiuni proprii deţinute pe termen lung','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1095','Acţiuni proprii reprezentând titluri deţinute de societatea absorbită la societatea absorbantă','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('11','Rezultatul reportat','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('117','Rezultatul reportat','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1171','Rezultatul reportat reprezentând profitul nerepartizat sau pierderea neacoperită','bifunctional');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1172','Rezultatul reportat provenit din adoptarea pentru prima dată a IAS, mai puţin IAS 29','bifunctional');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1173','Rezultatul reportat provenit din modificările politicilor contabile','bifunctional');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1174','Rezultatul reportat provenit din corectarea erorilor contabile','bifunctional');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1175','Rezultatul reportat reprezentând surplusul realizat din rezerve din reevaluare','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1176','Rezultatul reportat provenit din trecerea la aplicarea reglementărilor contabile conforme cu directivele europene','bifunctional');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('12','Rezultatul exerciţiului financiar','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('121','Profit sau pierdere','bifunctional');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('129','Repartizarea profitului','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('14','Câştiguri sau pierderi legate de emiterea, răscumpărarea, vânzarea, cedarea cu titlu gratuit sau anularea instrumentelor de capitaluri proprii','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('141','Câştiguri legate de vânzarea sau anularea instrumentelor de capitaluri proprii','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1411','Câştiguri legate de vânzarea instrumentelor de capitaluri proprii','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1412','Câştiguri legate de anularea instrumentelor de capitaluri proprii','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('149','Pierderi legate de emiterea, răscumpărarea, vânzarea, cedarea cu titlu gratuit sau anularea instrumentelor de capitaluri proprii','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1491','Pierderi rezultate din vânzarea instrumentelor de capitaluri proprii','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1495','Pierderi rezultate din reorganizări, care sunt determinate de anularea titlurilor deţinute','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1498','Alte pierderi legate de instrumentele de capitaluri proprii','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('15','Provizioane','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('151','Provizioane','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1511','Provizioane pentru litigii','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1512','Provizioane pentru garanţii acordate clienţilor','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1513','Provizioane pentru dezafectare imobilizări corporale şi alte acţiuni similare legate de acestea','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1514','Provizioane pentru restructurare','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1515','Provizioane pentru pensii şi obligaţii similare','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1516','Provizioane pentru impozite','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1517','Provizioane pentru terminarea contractului de muncă','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1518','Alte provizioane','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('16','Împrumuturi şi datorii asimilate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('161','Împrumuturi din emisiuni de obligaţiuni','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1614','Împrumuturi externe din emisiuni de obligaţiuni garantate de stat','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1615','Împrumuturi externe din emisiuni de obligaţiuni garantate de bănci','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1617','Împrumuturi interne din emisiuni de obligaţiuni garantate de stat','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1618','Alte împrumuturi din emisiuni de obligaţiuni','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('162','Credite bancare pe termen lung','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1621','Credite bancare pe termen lung','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1622','Credite bancare pe termen lung nerambursate la scadenţă','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1623','Credite externe guvernamentale','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1624','Credite bancare externe garantate de stat','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1625','Credite bancare externe garantate de bănci','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1626','Credite de la trezoreria statului','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1627','Credite bancare interne garantate de stat','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('166','Datorii care privesc imobilizările financiare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1661','Datorii faţă de entităţile afiliate','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1663','Datorii faţă de entităţile asociate şi entităţile controlate în comun','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('167','Alte împrumuturi şi datorii asimilate','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('168','Dobânzi aferente împrumuturilor şi datoriilor asimilate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1681','Dobânzi aferente împrumuturilor din emisiuni de obligaţiuni','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1682','Dobânzi aferente creditelor bancare pe termen lung','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1685','Dobânzi aferente datoriilor faţă de entităţile afiliate','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1686','Dobânzi aferente datoriilor faţă de entităţile asociate şi entităţile controlate în comun','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1687','Dobânzi aferente altor împrumuturi şi datorii asimilate','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('169','Prime privind rambursarea obligaţiunilor şi a altor datorii','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1691','Prime privind rambursarea obligaţiunilor','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('1692','Prime privind rambursarea altor datorii','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2','Conturi de imobilizări','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('20','Imobilizări necorporale','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('201','Cheltuieli de constituire','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('203','Cheltuieli de dezvoltare','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('205','Concesiuni, brevete, licenţe, mărci comerciale, drepturi şi active similare','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('206','active necorporale de explorare şi evaluare a resurselor minerale','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('207','Fond comercial','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2071','Fond comercial pozitiv','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2075','Fond comercial negativ','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('208','Alte imobilizări necorporale','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('21','Imobilizări corporale','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('211','Terenuri şi amenajări de terenuri','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2111','Terenuri','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2112','Amenajări de terenuri','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('212','Construcţii','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('213','Instalaţii tehnice şi mijloace de transport','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2131','Echipamente tehnologice (maşini, utilaje şi instalaţii de lucru)','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2132','Aparate şi instalaţii de măsurare, control şi reglare','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2133','Mijloace de transport','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('214','Mobilier, aparatură birotică, echipamente de protecţie a valorilor umane şi materiale şi alte active corporale','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('215','Investiţii imobiliare','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('216','active corporale de explorare şi evaluare a resurselor minerale','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('217','active biologice productive','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('22','Imobilizări corporale în curs de aprovizionare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('223','Instalaţii tehnice şi mijloace de transport în curs de aprovizionare','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('224','Mobilier, aparatură birotică, echipamente de protecţie a valorilor umane şi materiale şi alte active corporale în curs de aprovizionare','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('227','active biologice productive în curs de aprovizionare','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('23','Imobilizări în curs','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('231','Imobilizări corporale în curs de execuţie','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('235','Investiţii imobiliare în curs de execuţie','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('26','Imobilizări financiare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('261','Acţiuni deţinute la entităţile afiliate','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('262','Acţiuni deţinute la entităţi asociate','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('263','Acţiuni deţinute la entităţi controlate în comun','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('264','Titluri puse în echivalenţă','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('265','Alte titluri imobilizate','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('266','Certificate verzi amânate','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('267','Creanţe imobilizate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2671','Sume de încasat de la entităţile afiliate','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2672','Dobânda aferentă sumelor de încasat de la entităţile afiliate','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2673','Creanţe faţă de entităţile asociate şi entităţile controlate în comun','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2674','Dobânda aferentă creanţelor faţă de entităţile asociate şi entităţile controlate în comun','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2675','Împrumuturi acordate pe termen lung','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2676','Dobânda aferentă împrumuturilor acordate pe termen lung','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2677','Obligaţiuni achiziţionate cu ocazia emisiunilor efectuate de terţi','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2678','Alte creanţe imobilizate','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2679','Dobânzi aferente altor creanţe imobilizate','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('269','Vărsăminte de efectuat pentru imobilizări financiare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2691','Vărsăminte de efectuat privind acţiunile deţinute la entităţile afiliate','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2692','Vărsăminte de efectuat privind acţiunile deţinute la entităţi asociate','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2693','Vărsăminte de efectuat privind acţiunile deţinute la entităţi controlate în comun','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2695','Vărsăminte de efectuat pentru alte imobilizări financiare','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('28','Amortizări privind imobilizările','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('280','Amortizări privind imobilizările necorporale','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2801','Amortizarea cheltuielilor de constituire','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2803','Amortizarea cheltuielilor de dezvoltare','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2805','Amortizarea concesiunilor, brevetelor, licenţelor, mărcilor comerciale, drepturilor şi activelor similare','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2806','Amortizarea activelor necorporale de explorare şi evaluare a resurselor minerale','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2807','Amortizarea fondului comercial','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2808','Amortizarea altor imobilizări necorporale','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('281','Amortizări privind imobilizările corporale','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2811','Amortizarea amenajărilor de terenuri','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2812','Amortizarea construcţiilor','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2813','Amortizarea instalaţiilor şi mijloacelor de transport','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2814','Amortizarea altor imobilizări corporale','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2815','Amortizarea investiţiilor imobiliare','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2816','Amortizarea activelor corporale de explorare şi evaluare a resurselor minerale','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2817','Amortizarea activelor biologice productive','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('29','Ajustări pentru deprecierea sau pierderea de valoare a imobilizărilor','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('290','Ajustări pentru deprecierea imobilizărilor necorporale','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2903','Ajustări pentru deprecierea cheltuielilor de dezvoltare','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2905','Ajustări pentru deprecierea concesiunilor, brevetelor, licenţelor, mărcilor comerciale, drepturilor şi activelor similare','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2906','Ajustări pentru deprecierea activelor necorporale de explorare şi evaluare a resurselor minerale','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2908','Ajustări pentru deprecierea altor imobilizări necorporale','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('291','Ajustări pentru deprecierea imobilizărilor corporale','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2911','Ajustări pentru deprecierea terenurilor şi amenajărilor de terenuri','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2912','Ajustări pentru deprecierea construcţiilor','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2913','Ajustări pentru deprecierea instalaţiilor şi mijloacelor de transport','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2914','Ajustări pentru deprecierea altor imobilizări corporale','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2915','Ajustări pentru deprecierea investiţiilor imobiliare','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2916','Ajustări pentru deprecierea activelor corporale de explorare şi evaluare a resurselor minerale','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2917','Ajustări pentru deprecierea activelor biologice productive','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('293','Ajustări pentru deprecierea imobilizărilor în curs de execuţie','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2931','Ajustări pentru deprecierea imobilizărilor corporale în curs de execuţie','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2935','Ajustări pentru deprecierea investiţiilor imobiliare în curs de execuţie','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('296','Ajustări pentru pierderea de valoare a imobilizărilor financiare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2961','Ajustări pentru pierderea de valoare a acţiunilor deţinute la entităţile afiliate','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2962','Ajustări pentru pierderea de valoare a acţiunilor deţinute la entităţi asociate şi entităţi controlate în comun','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2963','Ajustări pentru pierderea de valoare a altor titluri imobilizate','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2964','Ajustări pentru pierderea de valoare a sumelor de încasat de la entităţile afiliate','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2965','Ajustări pentru pierderea de valoare a creanţelor faţă de entităţile asociate şi entităţile controlate în comun','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2966','Ajustări pentru pierderea de valoare a împrumuturilor acordate pe termen lung','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('2968','Ajustări pentru pierderea de valoare a altor creanţe imobilizate','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('3','Conturi de stocuri şi producţie în curs de execuţie','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('30','Stocuri de materii prime şi materiale','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('301','Materii prime','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('302','Materiale consumabile','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('3021','Materiale auxiliare','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('3022','Combustibili','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('3023','Materiale pentru ambalat','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('3024','Piese de schimb','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('3025','Seminţe şi materiale de plantat','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('3026','Furaje','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('3028','Alte materiale consumabile','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('303','Materiale de natura obiectelor de inventar','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('308','Diferenţe de preţ la materii prime şi materiale','bifunctional');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('32','Stocuri în curs de aprovizionare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('321','Materii prime în curs de aprovizionare','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('322','Materiale consumabile în curs de aprovizionare','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('323','Materiale de natura obiectelor de inventar în curs de aprovizionare','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('326','active biologice de natura stocurilor în curs de aprovizionare','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('327','Mărfuri în curs de aprovizionare','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('328','Ambalaje în curs de aprovizionare','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('33','Producţie în curs de execuţie','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('331','Produse în curs de execuţie','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('332','Servicii în curs de execuţie','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('34','Produse','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('341','Semifabricate','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('345','Produse finite','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('346','Produse reziduale','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('347','Produse agricole','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('348','Diferenţe de preţ la produse','bifunctional');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('35','Stocuri aflate la terţi','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('351','Materii şi materiale aflate la terţi','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('354','Produse aflate la terţi','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('356','active biologice de natura stocurilor aflate la terţi','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('357','Mărfuri aflate la terţi','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('358','Ambalaje aflate la terţi','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('36','active biologice de natura stocurilor','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('361','active biologice de natura stocurilor','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('368','Diferenţe de preţ la active biologice de natura stocurilor','bifunctional');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('37','Mărfuri','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('371','Mărfuri','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('378','Diferenţe de preţ la mărfuri','bifunctional');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('38','Ambalaje','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('381','Ambalaje','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('388','Diferenţe de preţ la ambalaje','bifunctional');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('39','Ajustări pentru deprecierea stocurilor şi producţiei în curs de execuţie','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('391','Ajustări pentru deprecierea materiilor prime','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('392','Ajustări pentru deprecierea materialelor','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('3921','Ajustări pentru deprecierea materialelor consumabile','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('3922','Ajustări pentru deprecierea materialelor de natura obiectelor de inventar','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('393','Ajustări pentru deprecierea producţiei în curs de execuţie','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('394','Ajustări pentru deprecierea produselor','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('3941','Ajustări pentru deprecierea semifabricatelor','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('3945','Ajustări pentru deprecierea produselor finite','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('3946','Ajustări pentru deprecierea produselor reziduale','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('3947','Ajustări pentru deprecierea produselor agricole','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('395','Ajustări pentru deprecierea stocurilor aflate la terţi','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('3951','Ajustări pentru deprecierea materiilor şi materialelor aflate la terţi','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('3952','Ajustări pentru deprecierea semifabricatelor aflate la terţi','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('3953','Ajustări pentru deprecierea produselor finite aflate la terţi','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('3954','Ajustări pentru deprecierea produselor reziduale aflate la terţi','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('3955','Ajustări pentru deprecierea produselor agricole aflate la terţi','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('3956','Ajustări pentru deprecierea activelor biologice de natura stocurilor aflate la terţi','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('3957','Ajustări pentru deprecierea mărfurilor aflate la terţi','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('3958','Ajustări pentru deprecierea ambalajelor aflate la terţi','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('396','Ajustări pentru deprecierea activelor biologice de natura stocurilor','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('397','Ajustări pentru deprecierea mărfurilor','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('398','Ajustări pentru deprecierea ambalajelor','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4','Conturi de terţi','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('40','Furnizori şi conturi asimilate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('401','Furnizori','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('403','Efecte de plătit','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('404','Furnizori de imobilizări','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('405','Efecte de plătit pentru imobilizări','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('408','Furnizori - facturi nesosite','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('409','Furnizori - debitori','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4091','Furnizori - debitori pentru cumpărări de bunuri de natura stocurilor','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4092','Furnizori - debitori pentru prestări de servicii','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4093','Avansuri acordate pentru imobilizări corporale','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4094','Avansuri acordate pentru imobilizări necorporale','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('41','Clienţi şi conturi asimilate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('411','Clienţi','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4111','Clienţi','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4118','Clienţi incerţi sau în litigiu','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('413','Efecte de primit de la clienţi','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('418','Clienţi - facturi de întocmit','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('419','Clienţi - creditori','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('42','Personal şi conturi asimilate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('421','Personal - salarii datorate','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('423','Personal - ajutoare materiale datorate','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('424','Prime reprezentând participarea personalului la profit','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('425','Avansuri acordate personalului','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('426','Drepturi de personal neridicate','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('427','Reţineri din salarii datorate terţilor','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('428','Alte datorii şi creanţe în legătură cu personalul','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4281','Alte datorii în legătură cu personalul','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4282','Alte creanţe în legătură cu personalul','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('43','Asigurări sociale, protecţia socială şi conturi asimilate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('431','Asigurări sociale','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4311','Contribuţia unităţii la asigurările sociale','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4312','Contribuţia personalului la asigurările sociale','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4313','Contribuţia angajatorului pentru asigurările sociale de sănătate','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4314','Contribuţia angajaţilor pentru asigurările sociale de sănătate','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4315','Contribuţia de asigurări sociale','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4316','Contribuţia de asigurări sociale de sănătate','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4318','Alte contribuţii pentru asigurările sociale de sănătate1','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('436','Contribuţia asiguratorie pentru muncă','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('437','Ajutor de şomaj','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4371','Contribuţia unităţii la fondul de şomaj','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4372','Contribuţia personalului la fondul de şomaj','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('438','Alte datorii şi creanţe sociale','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4381','Alte datorii sociale','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4382','Alte creanţe sociale','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('44','Bugetul statului, fonduri speciale şi conturi asimilate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('441','Impozitul pe profit şi alte impozite','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4411','Impozitul pe profit','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4415','Impozitul specific unor activităţi','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4418','Impozitul pe venit','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('442','Taxa pe valoarea adăugată','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4423','TVA de plată','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4424','TVA de recuperat','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4426','TVA deductibilă','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4427','TVA colectată','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4428','TVA neexigibilă','bifunctional');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('444','Impozitul pe venituri de natura salariilor','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('445','Subvenţii','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4451','Subvenţii guvernamentale','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4452','Împrumuturi nerambursabile cu caracter de subvenţii','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4458','Alte sume primite cu caracter de subvenţii','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('446','Alte impozite, taxe şi vărsăminte asimilate','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('447','Fonduri speciale - taxe şi vărsăminte asimilate','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('448','Alte datorii şi creanţe cu bugetul statului','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4481','Alte datorii faţă de bugetul statului','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4482','Alte creanţe privind bugetul statului','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('45','Grup şi acţionari/asociaţi','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('451','Decontări între entităţile afiliate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4511','Decontări între entităţile afiliate','bifunctional');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4518','Dobânzi aferente decontărilor între entităţile afiliate','bifunctional');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('453','Decontări cu entităţile asociate şi entităţile controlate în comun','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4531','Decontări cu entităţile asociate şi entităţile controlate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4538','Dobânzi aferente decontărilor cu entităţile asociate şi entităţile controlate în comun','bifunctional');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('455','Sume datorate acţionarilor/asociaţilor','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4551','Acţionari/Asociaţi - conturi curente','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4558','Acţionari/Asociaţi - dobânzi la conturi curente','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('456','Decontări cu acţionarii/asociaţii privind capitalul','bifunctional');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('457','Dividende de plată','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('458','Decontări din operaţiuni în participaţie','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4581','Decontări din operaţiuni în participaţie - pasiv','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4582','Decontări din operaţiuni în participaţie - activ','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('46','Debitori şi creditori diverşi','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('461','Debitori diverşi','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('462','Creditori diverşi','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('463','Creanţe reprezentând dividende repartizate în cursul exerciţiului financiar','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('466','Decontări din operaţiuni de fiducie','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4661','Datorii din operaţiuni de fiducie','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4662','Creanţe din operaţiuni de fiducie','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('47','Conturi de subvenţii, regularizare şi asimilate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('471','Cheltuieli înregistrate în avans','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('472','Venituri înregistrate în avans','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('473','Decontări din operaţiuni în curs de clarificare','bifunctional');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('475','Subvenţii pentru investiţii','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4751','Subvenţii guvernamentale pentru investiţii','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4752','Împrumuturi nerambursabile cu caracter de subvenţii pentru investiţii','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4753','Donaţii pentru investiţii','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4754','Plusuri de inventar de natura imobilizărilor','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4758','Alte sume primite cu caracter de subvenţii pentru investiţii','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('478','Venituri în avans aferente activelor primite prin transfer de la clienţi','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('48','Decontări în cadrul unităţii','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('481','Decontări între unitate şi subunităţi','bifunctional');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('482','Decontări între subunităţi','bifunctional');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('49','Ajustări pentru deprecierea creanţelor','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('490','Ajustări pentru deprecierea creanţelor reprezentând avansuri acordate furnizorilor','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4901','Ajustări pentru deprecierea creanţelor aferente cumpărărilor de bunuri de natura stocurilor','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4902','Ajustări pentru deprecierea creanţelor aferente prestărilor de servicii','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4903','Ajustări pentru deprecierea creanţelor aferente imobilizărilor corporale','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('4904','Ajustări pentru deprecierea creanţelor aferente imobilizărilor necorporale','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('491','Ajustări pentru deprecierea creanţelor - clienţi','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('495','Ajustări pentru deprecierea creanţelor - decontări în cadrul grupului şi cu acţionarii/asociaţii','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('496','Ajustări pentru deprecierea creanţelor - debitori diverşi','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('5','Conturi de trezorerie','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('50','Investiţii pe termen scurt','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('501','Acţiuni deţinute la entităţile afiliate','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('505','Obligaţiuni emise şi răscumpărate','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('506','Obligaţiuni','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('507','Certificate verzi primite','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('508','Alte investiţii pe termen scurt şi creanţe asimilate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('5081','Alte titluri de plasament','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('5088','Dobânzi la obligaţiuni şi titluri de plasament','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('509','Vărsăminte de efectuat pentru investiţiile pe termen scurt','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('5091','Vărsăminte de efectuat pentru acţiunile deţinute la entităţile afiliate','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('5092','Vărsăminte de efectuat pentru alte investiţii pe termen scurt','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('51','Conturi la bănci','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('511','Valori de încasat','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('5112','Cecuri de încasat','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('5113','Efecte de încasat','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('5114','Efecte remise spre scontare','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('512','Conturi curente la bănci','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('5121','Conturi la bănci în lei','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('5124','Conturi la bănci în valută','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('5125','Sume în curs de decontare','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('5126','Conturi la bănci în lei - TVA defalcat','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('5127','Conturi la bănci în valută - TVA defalcat','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('518','Dobânzi','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('5186','Dobânzi de plătit','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('5187','Dobânzi de încasat','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('519','Credite bancare pe termen scurt','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('5191','Credite bancare pe termen scurt','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('5192','Credite bancare pe termen scurt nerambursate la scadenţă','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('5193','Credite externe guvernamentale','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('5194','Credite externe garantate de stat','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('5195','Credite externe garantate de bănci','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('5196','Credite de la Trezoreria Statului','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('5197','Credite interne garantate de stat','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('5198','Dobânzi aferente creditelor bancare pe termen scurt','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('53','Casa','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('531','Casa','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('5311','Casa în lei','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('5314','Casa în valută','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('532','Alte valori','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('5321','Timbre fiscale şi poştale','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('5322','Bilete de tratament şi odihnă','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('5323','Tichete şi bilete de călătorie','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('5328','Alte valori','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('54','Acreditive','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('541','Acreditive','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('5411','Acreditive în lei','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('5414','Acreditive în valută','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('542','Avansuri de trezorerie','activ');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('58','Viramente interne','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('581','Viramente interne','bifunctional');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('59','Ajustări pentru pierderea de valoare a conturilor de trezorerie','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('591','Ajustări pentru pierderea de valoare a acţiunilor deţinute la entităţile afiliate','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('595','Ajustări pentru pierderea de valoare a obligaţiunilor emise şi răscumpărate','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('596','Ajustări pentru pierderea de valoare a obligaţiunilor','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('598','Ajustări pentru pierderea de valoare a altor investiţii pe termen scurt şi creanţe asimilate','pasiv');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6','Conturi de cheltuieli','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('60','Cheltuieli privind stocurile','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('601','Cheltuieli cu materiile prime','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('602','Cheltuieli cu materialele consumabile','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6021','Cheltuieli cu materialele auxiliare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6022','Cheltuieli privind combustibilii','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6023','Cheltuieli privind materialele pentru ambalat','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6024','Cheltuieli privind piesele de schimb','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6025','Cheltuieli privind seminţele şi materialele de plantat','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6026','Cheltuieli privind furajele','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6028','Cheltuieli privind alte materiale consumabile','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('603','Cheltuieli privind materialele de natura obiectelor de inventar','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('604','Cheltuieli privind materialele nestocate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('605','Cheltuieli privind energia şi apa','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('606','Cheltuieli privind activele biologice de natura stocurilor','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('607','Cheltuieli privind mărfurile','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('608','Cheltuieli privind ambalajele','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('609','Reduceri comerciale primite','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('61','Cheltuieli cu serviciile executate de terţi','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('611','Cheltuieli cu întreţinerea şi reparaţiile','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('612','Cheltuieli cu redevenţele, locaţiile de gestiune şi chiriile','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('613','Cheltuieli cu primele de asigurare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('614','Cheltuieli cu studiile şi cercetările','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('615','Cheltuieli cu pregătirea personalului','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('62','Cheltuieli cu alte servicii executate de terţi','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('621','Cheltuieli cu colaboratorii','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('622','Cheltuieli privind comisioanele şi onorariile','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('623','Cheltuieli de protocol, reclamă şi publicitate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6231','Cheltuieli de protocol','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6232','Cheltuieli de reclamă şi publicitate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('624','Cheltuieli cu transportul de bunuri şi personal','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('625','Cheltuieli cu deplasări, detaşări şi transferări','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('626','Cheltuieli poştale şi taxe de telecomunicaţii','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('627','Cheltuieli cu serviciile bancare şi asimilate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('628','Alte cheltuieli cu serviciile executate de terţi','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('63','Cheltuieli cu alte impozite, taxe şi vărsăminte asimilate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('635','Cheltuieli cu alte impozite, taxe şi vărsăminte asimilate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('64','Cheltuieli cu personalul','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('641','Cheltuieli cu salariile personalului','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('642','Cheltuieli cu avantajele în natură şi tichetele acordate salariaţilor','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6421','Cheltuieli cu avantajele în natură acordate salariaţilor','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6422','Cheltuieli cu tichetele acordate salariaţilor','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('643','Cheltuieli cu remunerarea în instrumente de capitaluri proprii','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('644','Cheltuieli cu primele reprezentând participarea personalului la profit','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('645','Cheltuieli privind asigurările şi protecţia socială','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6451','Cheltuiei privind contribuţia unităţii la asigurările sociale','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6452','Cheltuiei privind contribuţia unităţii pentru ajutorul de şomaj','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6453','Cheltuiei privind contribuţia angajatorului pentru asigurările sociale de sănătate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6455','Cheltuiei privind contribuţia unităţii la asigurările de viaţă','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6456','Cheltuiei privind contribuţia unităţii la fondurile de pensii facultative','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6457','Cheltuiei privind contribuţia unităţii la primele de asigurare voluntară de sănătate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6458','Alte cheltuieli privind asigurările şi protecţia socială','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('646','Cheltuieli privind contribuţia asiguratorie pentru muncă','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('65','Alte cheltuieli de exploatare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('651','Cheltuieli din operaţiuni de fiducie','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6511','Cheltuieli ocazionate de constituirea fiduciei','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6512','Cheltuieli din derularea operaţiunilor de fiducie','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6513','Cheltuieli din lichidarea operaţiunilor de fiducie','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6865','Cheltuieli financiare privind amortizarea diferenţelor aferente titlurilor de stat','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('652','Cheltuieli cu protecţia mediului înconjurător','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('654','Pierderi din creanţe şi debitori diverşi','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('655','Cheltuieli din reevaluarea imobilizărilor corporale','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('658','Alte cheltuieli de exploatare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6581','Despăgubiri, amenzi şi penalităţi','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6582','Donaţii acordate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6583','Cheltuieli privind activele cedate şi alte operaţiuni de capital','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6584','Cheltuieli cu sumele sau bunurile acordate ca sponsorizări1','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6586','Cheltuieli reprezentând transferuri şi contribuţii datorate în baza unor acte normative speciale','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6587','Cheltuieli privind calamităţile şi alte evenimente similare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6588','Alte cheltuieli de exploatare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('66','Cheltuieli financiare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('663','Pierderi din creanţe legate de participaţii','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('664','Cheltuieli privind investiţiile financiare cedate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6641','Cheltuieli privind imobilizările financiare cedate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6642','Pierderi din investiţiile pe termen scurt cedate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('665','Cheltuieli din diferenţe de curs valutar','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6651','Diferenţe nefavorabile de curs valutar legate de elementele monetare exprimate în valută','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6652','Diferenţe nefavorabile de curs valutar din evaluarea elementelor monetare care fac parte din investiţia netă într-o entitate străină','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('666','Cheltuieli privind dobânzile','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('667','Cheltuieli privind sconturile acordate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('668','Alte cheltuieli financiare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('68','Cheltuieli cu amortizările, provizioanele şi ajustările pentru depreciere sau pierdere de valoare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('681','Cheltuieli de exploatare privind amortizările, provizioanele şi ajustările pentru depreciere','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6811','Cheltuieli de exploatare privind amortizarea imobilizărilor','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6812','Cheltuieli de exploatare privind provizioanele','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6813','Cheltuieli de exploatare privind ajustările pentru deprecierea imobilizărilor','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6814','Cheltuieli de exploatare privind ajustările pentru deprecierea activelor circulante','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6817','Cheltuieli de exploatare privind ajustările pentru deprecierea fondului comercial','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6818','Cheltuieli de exploatare privind ajustările pentru deprecierea creanţelor reprezentând avansuri acordate furnizorilor','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('686','Cheltuieli financiare privind amortizările, provizioanele şi ajustările pentru pierdere de valoare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6861','Cheltuieli privind actualizarea provizioanelor','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6863','Cheltuieli financiare privind ajustările pentru pierderea de valoare a imobilizărilor financiare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6864','Cheltuieli financiare privind ajustările pentru pierderea de valoare a activelor circulante','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('6868','Cheltuieli financiare privind amortizarea primelor de rambursare a obligaţiunilor şi a altor datorii','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('69','Cheltuieli cu impozitul pe profit şi alte impozite','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('691','Cheltuieli cu impozitul pe profit','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('695','Cheltuieli cu impozitul specific unor activităţi1','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('698','Cheltuieli cu impozitul pe venit şi cu alte impozite care nu apar în elementele de mai sus','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7','Conturi de venituri','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('70','Cifra de afaceri netă','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('701','Venituri din vânzarea produselor finite, produselor agricole şi a activelor biologice de natura stocurilor','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7015','Venituri din vânzarea produselor finite','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7017','Venituri din vânzarea produselor agricole','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7018','Venituri din vânzarea activelor biologice de natura stocurilor','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('702','Venituri din vânzarea semifabricatelor','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('703','Venituri din vânzarea produselor reziduale','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('704','Venituri din servicii prestate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('705','Venituri din studii şi cercetări','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('706','Venituri din redevenţe, locaţii de gestiune şi chirii','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('707','Venituri din vânzarea mărfurilor','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('708','Venituri din activităţi diverse','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('709','Reduceri comerciale acordate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('71','Venituri aferente costului producţiei în curs de execuţie','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('711','Venituri aferente costurilor stocurilor de produse','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('712','Venituri aferente costurilor serviciilor în curs de execuţie','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('72','Venituri din producţia de imobilizări','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('721','Venituri din producţia de imobilizări necorporale','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('722','Venituri din producţia de imobilizări corporale','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('725','Venituri din producţia de investiţii imobiliare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('74','Venituri din subvenţii de exploatare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('741','Venituri din subvenţii de exploatare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7411','Venituri din subvenţii de exploatare aferente cifrei de afaceri','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7412','Venitur din subvenţii de exploatare pentru materii prime şi materiale','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7413','Venituri din subvenţii de exploatare pentru alte cheltuieli externe','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7414','Venituri din subvenţii de exploatare pentru plata personalului','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7415','Venituri din subvenţii de exploatare pentru asigurări şi protecţie socială','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7416','Venituri din subvenţii de exploatare pentru alte cheltuieli de exploatare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7417','Venituri din subvenţii de exploatare în caz de calamităţi şi alte evenimente similare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7418','Venituri din subvenţii de exploatare pentru dobânda datorată','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7419','Venituri din subvenţii de exploatare aferente altor venituri','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('75','Alte venituri din exploatare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('751','Venituri din operaţiuni de fiducie','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7511','Venituri ocazionate de constituirea fiduciei','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7512','Venituri din derularea operaţiunilor de fiducie','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7513','Venituri din lichidarea operaţiunilor de fiducie','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('754','Venituri din creanţe reactivate şi debitori diverşi','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('755','Venituri din reevaluarea imobilizărilor corporale','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('758','Alte venituri din exploatare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7581','Venituri din despăgubiri, amenzi şi penalităţi','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7582','Venituri din donaţii primite','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7583','Venituri din vânzarea activelor şi alte operaţiuni de capital','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7584','Venituri din subvenţii pentru investiţii','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7586','Venituri reprezentând transferuri cuvenite în baza unor acte normative speciale1','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7588','Alte venituri din exploatare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('76','Venituri financiare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('761','Venituri din imobilizări financiare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7611','Venituri din acţiuni deţinute la entităţile afiliate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7612','Venituri din acţiuni deţinute la entităţi asociate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7613','Venituri din acţiuni deţinute la entităţi controlate în comun','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7615','Venituri din alte imobilizări financiare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('762','Venituri din investiţii financiare pe termen scurt','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('764','Venituri din investiţii financiare cedate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7641','Venituri din imobilizări financiare cedate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7642','Câştiguri din investiţii pe termen scurt cedate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('765','Venituri din diferenţe de curs valutar','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7651','Diferenţe favorabile de curs valutar legate de elementele monetare exprimate în valută','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7652','Diferenţe favorabile de curs valutar din evaluarea elementelor monetare care fac parte din investiţia netă într-o entitate străină','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('766','Venituri din dobânzi','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('767','Venituri din sconturi obţinute','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('768','Alte venituri financiare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('78','Venituri din provizioane, amortizări şi ajustări pentru depreciere sau pierdere de valoare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('781','Venituri din provizioane şi ajustări pentru depreciere privind activitatea de exploatare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7812','Venituri din provizioane','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7813','Venituri din ajustări pentru deprecierea imobilizărilor','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7814','Venituri din ajustări pentru deprecierea activelor circulante','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7815','Venituri din fondul comercial negativ','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7818','Venituri din ajustări pentru deprecierea creanţelor reprezentând avansuri acordate furnizorilor','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('786','Venituri financiare din amortizări şi ajustări pentru pierdere de valoare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7863','Venituri financiare din ajustări pentru pierderea de valoare a imobilizărilor financiare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7864','Venituri financiare din ajustări pentru pierderea de valoare a activelor circulante','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('7865','Venituri financiare din amortizarea diferenţelor aferente titlurilor de stat','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('8','Conturi speciale','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('80','Conturi în afara bilanţului','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('801','Angajamente acordate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('8011','Giruri şi garanţii acordate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('8018','Alte angajamente acordate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('802','Angajamente primite','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('8021','Giruri şi garanţii primite','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('8028','Alte angajamente primite','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('803','Alte conturi în afara bilanţului','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('8031','Imobilizări corporale primite cu chirie sau în baza altor contracte similare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('8032','Valori materiale primite spre prelucrare sau reparare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('8033','Valori materiale primite în păstrare sau custodie','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('8034','Debitori scoşi din activ, urmăriţi în continuare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('8035','Stocuri de natura obiectelor de inventar date în folosinţă','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('8036','Redevenţe, locaţii de gestiune, chirii şi alte datorii asimilate','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('8037','Efecte scontate neajunse la scadenţă','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('8038','Bunuri primite în administrare, concesiune, cu chirie şi alte bunuri similare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('8039','Alte valori în afara bilanţului','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('804','Certificate verzi','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('805','Dobânzi aferente contractelor de leasing şi altor contracte asimilate, neajunse la scadenţă','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('8051','Dobânzi de plătit','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('8052','Dobânzi de încasat','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('806','Certificate de emisii de gaze cu efect de seră','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('807','active contingente','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('808','Datorii contingente','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('809','Creanţe preluate prin cesionare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('89','Bilanţ','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('891','Bilanţ de deschidere','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('892','Bilanţ de închidere','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('9','Conturi de gestiune','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('90','Decontări interne','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('901','Decontări interne privind cheltuielile','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('902','Decontări interne privind producţia obţinută','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('903','Decontări interne privind diferenţele de preţ','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('92','Conturi de calculaţie','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('921','Cheltuielile activităţii de bază','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('922','Cheltuielile activităţilor auxiliare','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('923','Cheltuieli indirecte de producţie','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('924','Cheltuieli generale de administraţie','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('925','Cheltuieli de desfacere','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('93','Costul producţiei','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('931','Costul producţiei obţinute','nespecificat');
INSERT INTO account_plan(account,acc_name,acc_type) VALUES ('933','Costul producţiei în curs de execuţie','nespecificat');
